#!/usr/bin/env python3
"""Bridge: mio-intelligence ideas.jsonl → mio-taskhub Idea system.

Scans ideas generated by mio.idea.generate and syncs them to mio-taskhub
via its REST API, creating Ideas with status=new.

Usage:
    python scripts/ideas_sync.py                    # sync all new ideas
    python scripts/ideas_sync.py --dry-run          # preview without creating
    python scripts/ideas_sync.py --project myproj   # filter by project
    python scripts/ideas_sync.py --backfill         # also push older ones
"""

import argparse
import json
import os
import sys
from pathlib import Path

import httpx

HUB_URL = os.environ.get("MIO_TASKHUB_URL", "http://127.0.0.1:48620/api/v1")
MIO_DATA_DIR = os.environ.get(
    "MIO_DATA_DIR",
    os.path.join(os.path.expanduser("~"), ".mio-intelligence"),
)
SYNC_STATE_FILE = os.path.join(MIO_DATA_DIR, "idea_sync_state.json")


def load_ideas_jsonl() -> list[dict]:
    path = os.path.join(MIO_DATA_DIR, "ideas.jsonl")
    if not os.path.exists(path):
        return []
    ideas = []
    with open(path, encoding="utf-8-sig") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                ideas.append(json.loads(line))
            except json.JSONDecodeError:
                continue
    return ideas


def load_sync_state() -> dict:
    if os.path.exists(SYNC_STATE_FILE):
        with open(SYNC_STATE_FILE, encoding="utf-8") as f:
            return json.load(f)
    return {"synced_ids": []}


def save_sync_state(state: dict):
    os.makedirs(os.path.dirname(SYNC_STATE_FILE), exist_ok=True)
    with open(SYNC_STATE_FILE, "w", encoding="utf-8") as f:
        json.dump(state, f, indent=2, ensure_ascii=False)


def list_taskhub_ideas(client: httpx.Client, project: str = "") -> list[dict]:
    params = {}
    if project:
        params["project"] = project
    try:
        r = client.get(f"{HUB_URL}/ideas", params=params)
        r.raise_for_status()
        return r.json().get("ideas", [])
    except Exception as e:
        print(f"  [WARN] Failed to list taskhub ideas: {e}")
        return []


def create_taskhub_idea(client: httpx.Client, idea: dict, project: str = "") -> dict | None:
    strategy = idea.get("provenance", {}).get("strategy", "")
    goal = idea.get("goal", "")
    labels = ["mio-intelligence", "auto-generated"]
    if strategy:
        labels.append(f"strategy:{strategy}")

    body = {
        "title": idea.get("title", "")[:200],
        "description": idea.get("description", ""),
        "project": project or idea.get("project", "") or "",
        "labels": labels,
    }
    try:
        r = client.post(f"{HUB_URL}/ideas", json=body)
        r.raise_for_status()
        return r.json()
    except Exception as e:
        print(f"  [ERROR] Failed to create idea '{body['title'][:60]}': {e}")
        return None


def sync(
    dry_run: bool = False,
    project: str = "",
    backfill: bool = False,
):
    ideas = load_ideas_jsonl()
    if not ideas:
        print("No ideas found in ideas.jsonl")
        return

    state = load_sync_state()
    synced = set(state.get("synced_ids", []))

    # Filter out already synced
    new_ideas = [i for i in ideas if i.get("id") not in synced]
    if not new_ideas:
        print(f"All {len(ideas)} ideas already synced.")
        return

    print(f"Found {len(new_ideas)} new ideas to sync (of {len(ideas)} total)")

    if dry_run:
        for idea in new_ideas:
            strategy = idea.get("provenance", {}).get("strategy", "?")
            print(f"  [DRY] [{strategy}] {idea.get('title', '?')[:80]}")
        return

    client = httpx.Client(timeout=10)

    # Check hub connectivity
    try:
        client.get(f"{HUB_URL}/tasks")
    except Exception as e:
        print(f"Cannot connect to mio-taskhub at {HUB_URL}: {e}")
        print("Start hub: python -m uvicorn mio_taskhub.main:app --port 48620")
        sys.exit(1)

    # Get existing taskhub ideas for dedup by title
    existing = list_taskhub_ideas(client, project)
    existing_titles = {i.get("title", "").strip().lower() for i in existing}

    created = 0
    skipped = 0
    for idea in new_ideas:
        title = idea.get("title", "").strip()
        if title.lower() in existing_titles:
            print(f"  [SKIP] Already exists: {title[:60]}")
            synced.add(idea["id"])
            skipped += 1
            continue

        result = create_taskhub_idea(client, idea, project)
        if result and "id" in result:
            print(f"  [OK] {title[:60]} → id={result['id']}")
            synced.add(idea["id"])
            existing_titles.add(title.lower())
            created += 1
        else:
            print(f"  [FAIL] {title[:60]}")

    client.close()

    state["synced_ids"] = list(synced)
    save_sync_state(state)
    print(f"\nDone: {created} created, {skipped} skipped (dedup), {len(new_ideas) - created - skipped} failed")


def main():
    parser = argparse.ArgumentParser(description="Sync mio-intelligence ideas to mio-taskhub")
    parser.add_argument("--dry-run", action="store_true", help="Preview without creating")
    parser.add_argument("--project", default="", help="Project name filter")
    parser.add_argument("--backfill", action="store_true", help="Also push older ideas")
    args = parser.parse_args()
    sync(dry_run=args.dry_run, project=args.project, backfill=args.backfill)


if __name__ == "__main__":
    main()
